### ISSUE TITLE
Returns only one word

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/AlexaRhyme#1]
main.js only returns one word per search. Many more are needed.

**Comment by inoridv** [comment]
Hello! I'll take care of this one :)

**Comment by ilanbiala** [comment]
@Web-Cam Since the return value is currently being `alert()`ed to the user, how should the n words per search be returned?

**Comment by Web-Cam** [comment]
I was just going to assign the return values to a variable, the alret was just for testing. Thanks for all the help so far !

**Comment by ilanbiala** [comment]
@Web-Cam take a look at the PR I referenced.
